fs/fs/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using fs.Models;
using fs.Models.IRepo;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace fs.Controllers
{
    [Authorize]
    public class UploadController : Controller
    {
        string conString = SQLConString.consTring();

        private IHostingEnvironment hostingEnv;
        private iUserManager _userManager;
        string empCode = "";
        public UploadController(IHostingEnvironment env, iUserManager userManager)
        {
            hostingEnv = env;
            _userManager = userManager;
            
        }

        public IActionResult Index()
        {
            return View();
        }

        //DBA
        public IActionResult Dba(IFormFile file)
        {
            empCode = _userManager.GetCurrentUser(this.HttpContext).employeeCode.ToString();
            var filename = ContentDispositionHeaderValue.Parse(file.ContentDisposition).FileName.Trim('"');

            var FileDic = "Files";
            string FilePath = Path.Combine(hostingEnv.WebRootPath, FileDic);
            if (!Directory.Exists(FilePath))
                Directory.CreateDirectory(FilePath);
            var fileName = file.FileName;
            var filePath = Path.Combine(FilePath, fileName);
            using (FileStream fs = System.IO.File.Create(filePath))
            {
                file.CopyTo(fs);
            }

            //get extension
            string extension = Path.GetExtension(filename);


            string exConString = string.Empty;

            switch (extension)
            {
                case ".xls": //Excel 97-03.
                    exConString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
                    break;
                case ".xlsx": //Excel 07 and above.
                    exConString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR=YES'";
                    break;
            }

            DataTable dt = new DataTable();
            exConString = string.Format(exConString, filePath);

            using (OleDbConnection connExcel = new OleDbConnection(exConString))
            {
                using (OleDbCommand cmdExcel = new OleDbCommand())
                {
                    using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                    {
                        cmdExcel.Connection = connExcel;

                        //Get the name of First Sheet.
                        connExcel.Open();
                        DataTable dtExcelSchema;
                        dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                        string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                        connExcel.Close();

                        //Read Data from First Sheet.
                        connExcel.Open();
                        cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                        odaExcel.SelectCommand = cmdExcel;
                        odaExcel.Fill(dt);
                        connExcel.Close();
                    }
                }
            }
            //your database connection string

            using (SqlConnection con = new SqlConnection(conString))
            {
                //DELETE RECORD
                if (dt.Rows.Count > 0) {
                    DataRow row = dt.Rows[0];
                    var rMonth = row[9];
                    var rYear = row[10];
                    con.Open();
                    string sqlD = "DELETE FROM dba WHERE month = '" + rMonth + "' and year = '" + rYear + "'";
                    SqlCommand cmdD = new SqlCommand(sqlD, con);
                    cmdD.ExecuteNonQuery();
                    con.Close();
                }
                

                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    DataRow row = dt.Rows[i];
                    int columnCount = dt.Columns.Count;
                    string[] columns = new string[columnCount];
                    for (int j = 0; j < columnCount; j++)
                    {
                        columns[j] = row[j].ToString();
                    }
                    con.Open();

                    decimal col3;
                    if (columns[3].Trim() == "") { col3 = 0; } else { col3 = Convert.ToDecimal(columns[3]); }
                    decimal col4;
                    if (columns[4].Trim() == "") { col4 = 0; } else { col4 = Convert.ToDecimal(columns[4]); }
                    decimal col5;
                    if (columns[5].Trim() == "") { col5 = 0; } else { col5 = Convert.ToDecimal(columns[5]); }
                    decimal col6;
                    if (columns[6].Trim() == "") { col6 = 0; } else { col6 = Convert.ToDecimal(columns[6]); }
                    decimal col7;
                    if (columns[7].Trim() == "") { col7 = 0; } else { col7 = Convert.ToDecimal(columns[7]); }
                    decimal col8;
                    if (columns[8].Trim() == "") { col8 = 0; } else { col8 = Convert.ToDecimal(columns[8]); }

                    string sql = "INSERT INTO dba(accntNo,accntTitle,accntType,consolidated,headOffice,northLuzon,southLuzon,visayas,mindanao,month,year,uploadedBy,uploadedDate)";
                    sql += "VALUES('" + columns[0] + "','" +
                        columns[1].Replace("'","") + "','" +
                        columns[2].Replace("'", "") + "','" +
                        col3 + "','" +
                        col4 + "','" +
                        col5 + "','" +
                        col6 + "','" +
                        col7 + "','" +
                        col8 + "','" +
                        columns[9] + "','" +
                        columns[10] + "','" +
                        empCode + "','" +
                        DateTime.Now + "')";
                    SqlCommand cmd = new SqlCommand(sql, con);

                    cmd.ExecuteNonQuery();
                    con.Close();
                    System.IO.File.Delete(filePath);
                }

            }
            //if the code reach here means everthing goes fine and excel data is imported into database
            ViewBag.Message = "File Imported and excel data saved into database";
            //return View("Index");

            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult GetDba()
        {
            List<dba> viewModel = new List<dba>();
            //string conString = @"Server=DESKTOP-6T4065S;Database=payslip;User Id=sa;Password=P@ssw0rd";
            using (SqlConnection con = new SqlConnection(conString))
            {
                con.Open();
                //38 columns
                string sql = "Select Distinct month,  year, uploadedDate, MONTH([month] + ' 1 ' + cast(year as nvarchar)) as monthNumber from dba order by year desc, MONTH([month] + ' 1 ' + cast(year as nvarchar)) asc";
                SqlCommand cmd = new SqlCommand(sql, con);
                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        viewModel.Add(new dba
                        {
                            month = reader.GetString(0).Trim().ToUpper(),
                            year = reader.GetInt32(1).ToString().Trim(),
                            uploadedDate = reader.GetDateTime(2).ToString("MMM dd, yyyy")
                        });
                    }
                }

                con.Close();
            }
            return Json(new { data = viewModel });
            // return View(viewModel);
        }

        [HttpDelete]
        public void DeleteDba(string month, string year)
        {
            using (SqlConnection con = new SqlConnection(conString))
            {
                con.Open();
                string sql = "DELETE FROM dba WHERE month = '" + month + "' and year = '" + year + "'";
                SqlCommand cmd = new SqlCommand(sql, con);
                cmd.ExecuteNonQuery();
                con.Close();
            }
        }

        [HttpGet]
        public IActionResult ViewDba(string month, string year)
        {
            List<dbaViewModel> viewModel = new List<dbaViewModel>();
            using (SqlConnection con = new SqlConnection(conString))
            {
                con.Open();
                string sql = "Select * From dba where month = '" + month + "' and year = '" + year + "'";
                SqlCommand cmd = new SqlCommand(sql, con);
                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        viewModel.Add(new dbaViewModel
                        {
                            id = reader.GetInt32(0),
                            accntNo = reader.GetString(1),
                            accntTitle = reader.GetString(2),
                            accntType = reader.GetString(3),
                            consolidated = reader.GetDecimal(4),
                            headOffice = reader.GetDecimal(5),
                            northLuzon = reader.GetDecimal(6),
                            southLuzon = reader.GetDecimal(7),
                            visayas = reader.GetDecimal(8),
                            mindanao = reader.GetDecimal(9),
                            month = reader.GetString(10),
                            year = reader.GetInt32(11).ToString()
                        });

fs/fs/Views/Upload/ViewCib.cshtml
@using  System.Text.RegularExpressions
@model List<cibViewModel>
<div class="row">

    <div class="col-md-12 ml-auto mr-auto">
        <div class="card">
            <div class="card-header ">
                <a class="btn btn-default btn-sm" asp-action="Index" asp-controller="Upload"> Back to Uploads</a>
                <h4 class="card-title text-center">FINANCE</h4>
                <h3 class="card-category text-center">
                    CASH IN BANK <br />
                    AS OF <b>@Model.FirstOrDefault().month.ToUpper() @Model.FirstOrDefault().year.ToUpper()</b>
                </h3>
            </div>
            <div class="card-body ">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="text-primary">
                            <tr>
                                <th>Bank</th>
                                <th class="text-right">Head Office</th>
                                <th class="text-right">Branches</th>
                                <th class="text-right">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var ho = "";
                                var branches = "";
                                decimal totalHo = 0;
                                decimal totalBranches = 0;
                                decimal totalAll = 0;

                                decimal perHo = 0;
                                decimal perBranches = 0;
                                decimal totalPer = 0;
                                foreach (var item in Model)
                                {

                                    if (item.ho < 0) { ho = "Red"; } else { ho = "Black"; }
                                    if (item.branches < 0) { branches = "Red"; } else { branches = "Black"; }

                                    var total = item.ho + item.branches;
                                    var cTotal = "";
                                    if (total < 0) { cTotal = "Red"; } else { cTotal = "Black"; }
                                    <tr>
                                        <td>

                                            @item.bank
                                        </td>
                                        <td class="text-right" style="color:@ho">
                                            @item.ho.ToString("#,###.00;(#,###.00);-")
                                        </td>
                                        <td class="text-right" style="color:@branches">
                                            @item.branches.ToString("#,###.00;(#,###.00);-")
                                        </td>
                                        <td class="text-right" style="color:@cTotal">
                                            <b>@total.ToString("#,###.00;(#,###.00);-")</b>
                                        </td>

                                    </tr>

                                    totalHo += item.ho;
                                    totalBranches += item.branches;

                                }
                                totalAll = totalHo + totalBranches;
                                perHo = (totalHo / totalAll) * 100;
                                perBranches = (totalBranches / totalAll) * 100;
                                totalPer = perHo + perBranches;
                            }
                        </tbody>
                        <tfoot>
                            <tr style="font-weight:bold">
                                <th>
                                    Cash in Bank
                                </th>
                                <th class="text-right">
                                    @totalHo.ToString("#,###.00;(#,###.00);-")
                                </th>
                                <th class="text-right">
                                    @totalBranches.ToString("#,###.00;(#,###.00);-")
                                </th>
                                <th class="text-right">
                                    @totalAll.ToString("#,###.00;(#,###.00);-")
                                </th>
                            </tr>
                            <tr style="font-weight:bold">
                                <th>
                                    % over total funds
                                </th>
                                <th class="text-right">
                                    @perHo.ToString("#,###.00;(#,###.00);-")%
                                </th>
                                <th class="text-right">
                                    @perBranches.ToString("#,###.00;(#,###.00);-")%
                                </th>
                                <th class="text-right">
                                    @totalPer.ToString("#,###.00;(#,###.00);-")%
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

fs/fs/Views/Upload/ViewDou.cshtml
@using  System.Text.RegularExpressions
@model List<douViewModel>
<div class="row">

    <div class="col-md-12 ml-auto mr-auto">
        <div class="card">
            <div class="card-header ">
                <a class="btn btn-default btn-sm" asp-action="Index" asp-controller="Upload"> Back to Uploads</a>
                <h4 class="card-title text-center">DOU</h4>
                <h3 class="card-category text-center">
                    DAILY OPERATIONAL UPDATES <br />
                    AS OF <b>@Model.FirstOrDefault().month.ToUpper() @Model.FirstOrDefault().year.ToUpper()</b>
                </h3>
            </div>
            <div class="card-body ">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="text-primary">
                            <tr>
                                <th>Particulars</th>
                                <th class="text-right">For the Day</th>
                                <th class="text-right">Cumulative</th>
                                <th class="text-right">For the Month</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var forTheDay = "";
                                var cumulative = "";
                                var forTheMonth = "";
                                foreach (var item in Model)
                                {
                                    
                                    if (item.forTheDay < 0) { forTheDay = "Red"; } else { forTheDay = "Black"; }
                                    if (item.cumulative < 0) { cumulative = "Red"; } else { cumulative = "Black"; }
                                    if (item.forTheMonth < 0) { forTheMonth = "Red"; } else { forTheMonth = "Black"; }

                                    <tr>
                                        <td>
                                            @*@item.particulars*@

                                            @{
                                                var q = "-----";
                                                var input = item.particulars.TrimEnd();
                                                string result = Regex.Replace(input, "^ ", q);
                                            }
                                            @result
                                        </td>
                                        <td class="text-right" style="color:@forTheDay">
                                            @item.forTheDay.ToString("#,###.00;(#,###.00);-")
                                        </td>
                                        <td class="text-right" style="color:@cumulative">
                                            @item.cumulative.ToString("#,###.00;(#,###.00);-")
                                        </td>
                                        <td class="text-right" style="color:@forTheMonth">
                                            @item.forTheMonth.ToString("#,###.00;(#,###.00);-")
                                        </td>

                                    </tr>

                                    //assetsCons += item.consolidated;

                                }
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

fs/fs/Views/Upload/ViewFinancialAssets.cshtml
@using  System.Text.RegularExpressions
@model List<financialAssetsViewModel>
<div class="row">

    <div class="col-md-12 ml-auto mr-auto">
        <div class="card">
            <div class="card-header ">
                <a class="btn btn-default btn-sm" asp-action="Index" asp-controller="Upload"> Back to Uploads</a>
                <h4 class="card-title text-center">FINANCE</h4>
                <h3 class="card-category text-center">
                    SHORT-TERM PLACEMENTS <br />
                    AS OF <b>@Model.FirstOrDefault().month.ToUpper() @Model.FirstOrDefault().year.ToUpper()</b>
                </h3>
            </div>
            <div class="card-body ">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="text-primary">
                            <tr>
                                <th>Particulars</th>
                                <th>Entity</th>
                                <th>Date Issued</th>
                                <th class="text-center">No. of Shares</th>
                                <th class="text-right">Closing Rate</th>
                                <th class="text-right">Market Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var closingRate = "";
                                var marketValue = "";
                               // decimal total = 0;
                                foreach (var item in Model)
                                {

                                    if (item.closingRate < 0) { closingRate = "Red"; } else { closingRate = "Black"; }
                                    if (item.marketValue < 0) { marketValue = "Red"; } else { marketValue = "Black"; }
                            <tr>
                                <td>
                                    @item.particulars
                                </td>
                                <td>
                                    @item.entity
                                </td>
                                <td>
                                    @item.dateIssued
                                </td>
                                <td class="text-center">
                                    @item.noShares
                                </td>
                                <td class="text-right" style="color:@closingRate">
                                    @item.closingRate.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@marketValue">
                                    @item.marketValue.ToString("#,###.00;(#,###.00);-")
                                </td>

                            </tr>

                                    //total += item.amount;
                                }
                            }
                        </tbody>
                        @*<tfoot>
                            <tr style="font-weight:bold">
                                <th>
                                    Total
                                </th>
                                <th class="text-right">
                                    @total.ToString("#,###.00;(#,###.00);-")
                                </th>
                            </tr>
                        </tfoot>*@
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

fs/fs/Views/Upload/ViewIncomeStatement.cshtml
@using  System.Text.RegularExpressions
@model List<incomeStatementViewModel>
<div class="row">

    <div class="col-md-12 ml-auto mr-auto">
        <div class="card">
            <div class="card-header ">
                <a class="btn btn-default btn-sm" asp-action="Index" asp-controller="Upload"> Back to Uploads</a>
                <h4 class="card-title text-center">BUDGET</h4>
                <h3 class="card-category text-center">
                    INCOME STATEMENT <br />
                    <br />
                    FOR THE YEAR <b>@Model.FirstOrDefault().year.ToUpper()</b>
                </h3>
            </div>
            <div class="card-body ">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="text-primary">
                            <tr>
                                <th>Account Title</th>
                                <th class="text-right">1</th>
                                <th class="text-right">2</th>
                                <th class="text-right">3</th>
                                <th class="text-right">4</th>
                                <th class="text-right">5</th>
                                <th class="text-right">6</th>
                                <th class="text-right">7</th>
                                <th class="text-right">8</th>
                                <th class="text-right">9</th>
                                <th class="text-right">10</th>
                                <th class="text-right">11</th>
                                <th class="text-right">12</th>
                                <th class="text-right">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var m1 = "";
                                var m2 = "";
                                var m3 = "";
                                var m4 = "";
                                var m5 = "";
                                var m6 = "";
                                var m7 = "";
                                var m8 = "";
                                var m9 = "";
                                var m10 = "";
                                var m11 = "";
                                var m12 = "";

                                foreach (var item in Model)
                                {

                                    if (item.m1 < 0) { m1 = "Red"; } else { m1 = "Black"; }
                                    if (item.m2 < 0) { m2 = "Red"; } else { m2 = "Black"; }
                                    if (item.m3 < 0) { m3 = "Red"; } else { m3 = "Black"; }
                                    if (item.m4 < 0) { m4 = "Red"; } else { m4 = "Black"; }
                                    if (item.m5 < 0) { m5 = "Red"; } else { m5 = "Black"; }
                                    if (item.m6 < 0) { m6 = "Red"; } else { m6 = "Black"; }
                                    if (item.m7 < 0) { m7 = "Red"; } else { m7 = "Black"; }
                                    if (item.m8 < 0) { m8 = "Red"; } else { m8 = "Black"; }
                                    if (item.m9 < 0) { m9 = "Red"; } else { m9 = "Black"; }
                                    if (item.m10 < 0) { m10 = "Red"; } else { m10 = "Black"; }
                                    if (item.m11 < 0) { m11 = "Red"; } else { m11 = "Black"; }
                                    if (item.m12 < 0) { m12 = "Red"; } else { m12 = "Black"; }

                                    var total = item.m1 + item.m2 + item.m3 + item.m4 + item.m5 + item.m6 + item.m7 + item.m8 + item.m9 + item.m10 + item.m11 + item.m12;
                            <tr>
                                <td>
                                    @item.accntTitle
                                </td>
                                <td class="text-right" style="color:@m1">
                                    @item.m1.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m2">
                                    @item.m2.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m3">
                                    @item.m3.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m4">
                                    @item.m4.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m5">
                                    @item.m5.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m6">
                                    @item.m6.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m7">
                                    @item.m7.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m8">
                                    @item.m8.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m9">
                                    @item.m9.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m10">
                                    @item.m10.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m11">
                                    @item.m11.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m12">
                                    @item.m12.ToString("#,###.00;(#,###.00);-")
                                </td>
                                <td class="text-right" style="color:@m12">
                                    <b>@total.ToString("#,###.00;(#,###.00);-")</b>
                                </td>
                            </tr>

                                    //assetsCons += item.consolidated;

                                }
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

fs/fs/Views/Upload/ViewShortTerm.cshtml
@using  System.Text.RegularExpressions
@model List<shortTermViewModel>
<div class="row">

    <div class="col-md-12 ml-auto mr-auto">
        <div class="card">
            <div class="card-header ">
                <a class="btn btn-default btn-sm" asp-action="Index" asp-controller="Upload"> Back to Uploads</a>
                <h4 class="card-title text-center">FINANCE</h4>
                <h3 class="card-category text-center">
                    SHORT-TERM PLACEMENTS <br />
                    AS OF <b>@Model.FirstOrDefault().month.ToUpper() @Model.FirstOrDefault().year.ToUpper()</b>
                </h3>
            </div>
            <div class="card-body ">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead class="text-primary">
                            <tr>
                                <th>Particulars</th>
                                <th class="text-right">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                var amount = "";
                                decimal total = 0;
                                foreach (var item in Model)
                                {

                                    if (item.amount < 0) { amount = "Red"; } else { amount = "Black"; }
                                    <tr>
                                        <td>

                                            @item.particulars
                                        </td>
                                        <td class="text-right" style="color:@amount">
                                            @item.amount.ToString("#,###.00;(#,###.00);-")
                                        </td>

                                    </tr>

                                    total += item.amount;
                                }
                            }
                        </tbody>
                        <tfoot>
                            <tr style="font-weight:bold">
                                <th>
                                    Total
                                </th>
                                <th class="text-right">
                                    @total.ToString("#,###.00;(#,###.00);-")
                                </th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>